# Generated by Django 2.0.4 on 2018-06-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20180609_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
